Probably fix missing argument for MieleClient
Reported by @vistalba , https://github.com/vistalba
in changelog https://github.com/HomeAssistant-Mods/home-assistant-miele/compare/a645f64...8686553

Logger: homeassistant.setup
Source: custom_components/miele/__init__.py:124
First occurred: 11:16:23 (1 occurrences)
Last logged: 11:16:23

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/miele/__init__.py", line 124, in async_setup
    client = MieleClient(hass.data[DOMAIN][DATA_OAUTH])
TypeError: __init__() missing 1 required positional argument: 'session'